import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const GuruFilter: NextPage = ({ token }: any) => {
  const router = useRouter();
  const { query } = router;

  const urlData = Object.keys(query).map((key) => {
    const k = key.replaceAll('amp;', '');
    return `${k}=${query[key]}`;
  });

  if (urlData.length === 0) {
    return <div>Loading...</div>;
  }

  // const completeUrl = '';
  // console.log(token);
  const completeUrl = `https://links.criptomaniacos.com.br/form/${token}?${urlData.join(
    '&'
  )}`;

  return (
    <div>
      <Head>
        <title>Criptomaniacos: Obrigado pelo cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <meta httpEquiv="refresh" content={`0; URL='${completeUrl}'`} /> */}
      </Head>

      <h1>Obrigado pelo seu cadastro</h1>
      <p>Você será redirecionado para a plataforma em 2 segundos.</p>
      <p>
        Caso não seja redirecionado, clique <a href={completeUrl}>aqui</a>.
      </p>
    </div>
  );
};

export async function getStaticPaths() {
  return {
    paths: [],
    fallback: true, // false or 'blocking'
  };
}

export async function getStaticProps({ params }: any) {
  const { token } = params;
  return {
    props: { token }, // will be passed to the page component as props
  };
}

export default GuruFilter;
